version: '3.8'

volumes:
    mongodb_data:
    mongodb_config:

services:
    db:
        image: mongo:4.2.16-rc0-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - type: volume
              source: mongodb_data
              target: /data/db
            - type: volume
              source: mongodb_config
              target: /data/configdb
    api:
        container_name: 'lightweight-netflix'
        build:
            context: ./
            labels:
                app.name: 'Lightweight Netflix'
                app.description: 'A simple Netflix API simulation'
                app.author: 'Mohammad Korra <muhammadkorra@gmail.com>'
        ports:
            - '4040:4040'
        environment:
            - 'MONGODB_URL=mongodb://db:27017?authSource=admin'
            - 'MONGODB_USERNAME=root'
            - 'MONGODB_PASSWORD=password'
            - 'JWT_PASSWORD=jwt-password'
        depends_on:
            - db
